torchrun --nproc_per_node=4 --master_port=20001 xiwu/train/fine_tuning/train_mem.py \
    --model_name_or_path lmsys/vicuna-13b-v1.5-16k \
    --data_path /data/zdzhang/datasets/hep_text_v1.0 \
    --bf16 True \
    --num_train_epochs 2 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1200 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_config "./xiwu/configs/fsdp_config.json" \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True
